CC=gcc
CFLAGS=-Wall -ansi -pedantic

exe1: exe1.o 
	$(CC) exe1.c -o exe1 $(CFLAGS)

exe2: exe2.o 
	$(CC) exe2.c -o exe2 $(CFLAGS)

exe3: exe3.o 
	$(CC) exe3.c -o exe3 $(CFLAGS)
clean:
	rm *.o
	rm exe?
